// Milestone 5, the Arabic root system.
// Every Arabic word is built from a 3-letter root (sometimes 4). Once you
// recognize a root, you can often guess the meaning of a new word just by
// seeing which pattern it follows. This module curates ~30 of the most
// pedagogically useful Quranic roots with their derivations.
// Portable pure-data module.

export interface RootDerivation {
    arabic: string;
    transliteration: string;
    meaning: string;
    form?: string;           // e.g. "verb (past)", "noun", "active participle"
    exampleVerse?: string;   // verse_key where this form appears
}

export interface ArabicRoot {
    id: string;
    root: string;            // 3 letters separated by spaces, e.g. "ك ت ب"
    coreMeaning: string;     // 1-sentence English gloss
    explanation: string;     // 2-3 sentences of pedagogy
    derivations: RootDerivation[];
    quranCount?: number;     // approximate number of occurrences across the Quran
    category: "Worship" | "Divine Attributes" | "Action" | "Perception" | "Character" | "Creation" | "Knowledge & Speech" | "Body & Self";
}

export const ROOTS: ArabicRoot[] = [
    // ─────────────────────────────────────────── KNOWLEDGE & SPEECH ──
    {
        id: "k-t-b",
        root: "ك ت ب",
        coreMeaning: "to write; to prescribe; a book",
        explanation: "This root also carries the idea of 'prescribing' (writing something into effect, making it obligatory). Hence كَتَبَ in legal contexts means 'He made it binding.'",
        quranCount: 319,
        category: "Knowledge & Speech",
        derivations: [
            { arabic: "كَتَبَ", transliteration: "kataba", meaning: "he wrote / he prescribed", form: "verb (past)", exampleVerse: "2:183" },
            { arabic: "يَكْتُبُ", transliteration: "yaktubu", meaning: "he writes", form: "verb (present)", exampleVerse: "2:282" },
            { arabic: "كِتَاب", transliteration: "kitab", meaning: "book, scripture", form: "noun", exampleVerse: "2:2" },
            { arabic: "كَاتِب", transliteration: "katib", meaning: "writer, scribe", form: "active participle", exampleVerse: "2:282" },
            { arabic: "مَكْتُوب", transliteration: "maktub", meaning: "written, destined", form: "passive participle", exampleVerse: "7:157" },
            { arabic: "كُتُب", transliteration: "kutub", meaning: "books (plural)", form: "noun (plural)", exampleVerse: "98:2" },
        ],
    },
    {
        id: "q-r-a",
        root: "ق ر أ",
        coreMeaning: "to read, to recite",
        explanation: "The very name of the Quran comes from this root, القُرْآن literally means 'The Recitation'. The first word revealed to the Prophet ﷺ was اِقْرَأْ ('Read!').",
        quranCount: 88,
        category: "Knowledge & Speech",
        derivations: [
            { arabic: "قَرَأَ", transliteration: "qara'a", meaning: "he recited", form: "verb (past)", exampleVerse: "17:45" },
            { arabic: "اِقْرَأْ", transliteration: "iqra'", meaning: "read! recite!", form: "imperative", exampleVerse: "96:1" },
            { arabic: "قُرْآن", transliteration: "Qur'an", meaning: "the Recitation", form: "noun", exampleVerse: "2:185" },
            { arabic: "مَقْرُوء", transliteration: "maqru'", meaning: "read, recited", form: "passive participle" },
        ],
    },
    {
        id: "q-w-l",
        root: "ق و ل",
        coreMeaning: "to say, to speak",
        explanation: "One of the most frequent roots in the Quran. قَالَ appears ~1700 times because Allah recounts what prophets, angels, and people 'said' again and again.",
        quranCount: 1722,
        category: "Knowledge & Speech",
        derivations: [
            { arabic: "قَالَ", transliteration: "qala", meaning: "he said", form: "verb (past)", exampleVerse: "2:30" },
            { arabic: "يَقُولُ", transliteration: "yaqulu", meaning: "he says", form: "verb (present)", exampleVerse: "2:8" },
            { arabic: "قُلْ", transliteration: "qul", meaning: "say!", form: "imperative", exampleVerse: "112:1" },
            { arabic: "قَوْل", transliteration: "qawl", meaning: "speech, statement", form: "noun", exampleVerse: "23:68" },
            { arabic: "قَائِل", transliteration: "qa'il", meaning: "speaker", form: "active participle", exampleVerse: "23:100" },
        ],
    },
    {
        id: "a-l-m",
        root: "ع ل م",
        coreMeaning: "to know; knowledge",
        explanation: "From this root come 'knowledge' (عِلْم), 'scholar' (عَالِم), 'world' (عَالَم, because it makes Allah known), and Allah's name 'The All-Knowing' (العَلِيم).",
        quranCount: 854,
        category: "Knowledge & Speech",
        derivations: [
            { arabic: "عَلِمَ", transliteration: "'alima", meaning: "he knew", form: "verb (past)", exampleVerse: "2:30" },
            { arabic: "يَعْلَمُ", transliteration: "ya'lamu", meaning: "he knows", form: "verb (present)", exampleVerse: "2:33" },
            { arabic: "عِلْم", transliteration: "'ilm", meaning: "knowledge", form: "noun", exampleVerse: "20:114" },
            { arabic: "عَالِم", transliteration: "'alim", meaning: "a scholar, one who knows", form: "active participle", exampleVerse: "35:28" },
            { arabic: "عَلِيم", transliteration: "'Alim", meaning: "The All-Knowing (divine name)", form: "intensive adjective", exampleVerse: "2:32" },
            { arabic: "مَعْلُوم", transliteration: "ma'lum", meaning: "known, fixed", form: "passive participle", exampleVerse: "15:21" },
            { arabic: "عَلَّمَ", transliteration: "'allama", meaning: "he taught", form: "verb (form II)", exampleVerse: "2:31" },
            { arabic: "تَعْلِيم", transliteration: "ta'lim", meaning: "teaching", form: "verbal noun" },
            { arabic: "عَالَم", transliteration: "'alam", meaning: "world", form: "noun", exampleVerse: "1:2" },
        ],
    },
    {
        id: "dh-k-r",
        root: "ذ ك ر",
        coreMeaning: "to remember, to mention",
        explanation: "The root of 'dhikr', the remembrance of Allah. The same root means 'male' (ذَكَر), the idea being that the male 'mentions' / carries on the family name.",
        quranCount: 292,
        category: "Knowledge & Speech",
        derivations: [
            { arabic: "ذَكَرَ", transliteration: "dhakara", meaning: "he remembered, mentioned", form: "verb (past)", exampleVerse: "2:152" },
            { arabic: "يَذْكُرُ", transliteration: "yadhkuru", meaning: "he remembers", form: "verb (present)", exampleVerse: "2:200" },
            { arabic: "اُذْكُرْ", transliteration: "udhkur", meaning: "remember! mention!", form: "imperative", exampleVerse: "2:152" },
            { arabic: "ذِكْر", transliteration: "dhikr", meaning: "remembrance, reminder", form: "noun", exampleVerse: "15:9" },
            { arabic: "ذَاكِر", transliteration: "dhakir", meaning: "one who remembers", form: "active participle", exampleVerse: "33:35" },
            { arabic: "مَذْكُور", transliteration: "madhkur", meaning: "mentioned", form: "passive participle", exampleVerse: "76:1" },
        ],
    },

    // ─────────────────────────────────────────── WORSHIP ──
    {
        id: "a-b-d",
        root: "ع ب د",
        coreMeaning: "to serve, to worship",
        explanation: "The word عَبْد (servant) and عِبَادَة (worship) come from this root. The core idea is devotional service, Allah is العَبْد's Master, and humans are His 'ibad (slaves in the honorable sense).",
        quranCount: 275,
        category: "Worship",
        derivations: [
            { arabic: "عَبَدَ", transliteration: "'abada", meaning: "he worshiped", form: "verb (past)", exampleVerse: "1:5" },
            { arabic: "يَعْبُدُ", transliteration: "ya'budu", meaning: "he worships", form: "verb (present)", exampleVerse: "51:56" },
            { arabic: "اعْبُدُوا", transliteration: "u'budu", meaning: "worship! (plural)", form: "imperative", exampleVerse: "2:21" },
            { arabic: "عَبْد", transliteration: "'abd", meaning: "servant, slave (of Allah)", form: "noun", exampleVerse: "2:23" },
            { arabic: "عِبَادَة", transliteration: "'ibadah", meaning: "worship", form: "verbal noun", exampleVerse: "7:206" },
            { arabic: "عِبَاد", transliteration: "'ibad", meaning: "servants (plural)", form: "noun (plural)", exampleVerse: "25:63" },
            { arabic: "مَعْبُود", transliteration: "ma'bud", meaning: "one who is worshiped", form: "passive participle" },
        ],
    },
    {
        id: "s-l-w",
        root: "ص ل و",
        coreMeaning: "to pray; to invoke blessing",
        explanation: "The root of صَلَاة (prayer) and the blessings invoked on the Prophet ﷺ (اللَّهُمَّ صَلِّ عَلَى مُحَمَّد).",
        quranCount: 99,
        category: "Worship",
        derivations: [
            { arabic: "صَلَّى", transliteration: "salla", meaning: "he prayed; Allah invoked blessing", form: "verb (form II)", exampleVerse: "87:15" },
            { arabic: "يُصَلِّي", transliteration: "yusalli", meaning: "he prays", form: "verb (present)", exampleVerse: "2:3" },
            { arabic: "صَلَاة", transliteration: "salah", meaning: "prayer", form: "noun", exampleVerse: "2:3" },
            { arabic: "صَلَوَات", transliteration: "salawat", meaning: "prayers (plural)", form: "noun", exampleVerse: "2:238" },
            { arabic: "مُصَلِّي", transliteration: "musalli", meaning: "one who prays", form: "active participle", exampleVerse: "74:43" },
            { arabic: "مُصَلَّى", transliteration: "musalla", meaning: "place of prayer", form: "noun of place", exampleVerse: "2:125" },
        ],
    },
    {
        id: "s-j-d",
        root: "س ج د",
        coreMeaning: "to prostrate",
        explanation: "The root of the word 'masjid' (مَسْجِد, place of prostration). Sujud is the deepest form of worship, the forehead on the ground acknowledging the Creator.",
        quranCount: 91,
        category: "Worship",
        derivations: [
            { arabic: "سَجَدَ", transliteration: "sajada", meaning: "he prostrated", form: "verb (past)", exampleVerse: "2:34" },
            { arabic: "يَسْجُدُ", transliteration: "yasjudu", meaning: "he prostrates", form: "verb (present)", exampleVerse: "22:18" },
            { arabic: "اسْجُدُوا", transliteration: "usjudu", meaning: "prostrate! (plural)", form: "imperative", exampleVerse: "2:34" },
            { arabic: "سُجُود", transliteration: "sujud", meaning: "prostration", form: "verbal noun", exampleVerse: "22:18" },
            { arabic: "سَاجِد", transliteration: "sajid", meaning: "one who prostrates", form: "active participle", exampleVerse: "15:98" },
            { arabic: "مَسْجِد", transliteration: "masjid", meaning: "place of prostration, mosque", form: "noun of place", exampleVerse: "2:144" },
        ],
    },
    {
        id: "h-m-d",
        root: "ح م د",
        coreMeaning: "to praise (Allah)",
        explanation: "The root of الحَمْد (all praise) and the names محمد (Muhammad, 'the praised') and أحمد (Ahmad). The very first full word of the Quran after Bismillah is 'Alhamdulillah'.",
        quranCount: 68,
        category: "Worship",
        derivations: [
            { arabic: "حَمِدَ", transliteration: "hamida", meaning: "he praised", form: "verb (past)" },
            { arabic: "يَحْمَدُ", transliteration: "yahmadu", meaning: "he praises", form: "verb (present)" },
            { arabic: "حَمْد", transliteration: "hamd", meaning: "praise", form: "noun", exampleVerse: "1:2" },
            { arabic: "حَامِد", transliteration: "hamid", meaning: "one who praises", form: "active participle", exampleVerse: "9:112" },
            { arabic: "حَمِيد", transliteration: "Hamid", meaning: "The Praiseworthy (divine name)", form: "intensive adjective", exampleVerse: "11:73" },
            { arabic: "مُحَمَّد", transliteration: "Muhammad", meaning: "the one praised abundantly", form: "passive intensive", exampleVerse: "48:29" },
            { arabic: "أَحْمَد", transliteration: "Ahmad", meaning: "the most praised", form: "comparative", exampleVerse: "61:6" },
        ],
    },

    // ─────────────────────────────────────────── DIVINE ATTRIBUTES ──
    {
        id: "r-h-m",
        root: "ر ح م",
        coreMeaning: "mercy, compassion, womb",
        explanation: "The most repeated divine attribute. Allah calls Himself ar-Rahman and ar-Rahim. The same root gives us the word for 'womb' (رَحِم), because a womb is the most merciful of places in creation.",
        quranCount: 339,
        category: "Divine Attributes",
        derivations: [
            { arabic: "رَحِمَ", transliteration: "rahima", meaning: "he had mercy", form: "verb (past)", exampleVerse: "12:53" },
            { arabic: "يَرْحَمُ", transliteration: "yarhamu", meaning: "he has mercy", form: "verb (present)", exampleVerse: "7:49" },
            { arabic: "رَحْمَة", transliteration: "rahmah", meaning: "mercy", form: "noun", exampleVerse: "21:107" },
            { arabic: "الرَّحْمَٰن", transliteration: "ar-Rahman", meaning: "The Most Compassionate (divine name)", form: "intensive noun", exampleVerse: "1:3" },
            { arabic: "الرَّحِيم", transliteration: "ar-Rahim", meaning: "The Most Merciful (divine name)", form: "intensive adjective", exampleVerse: "1:3" },
            { arabic: "رَاحِم", transliteration: "rahim", meaning: "one who shows mercy", form: "active participle", exampleVerse: "23:109" },
            { arabic: "أَرْحَم", transliteration: "arham", meaning: "most merciful", form: "superlative", exampleVerse: "12:64" },
        ],
    },
    {
        id: "gh-f-r",
        root: "غ ف ر",
        coreMeaning: "to forgive, to cover",
        explanation: "The root's core meaning is 'to cover' (hence the Arabic helmet was called مِغْفَر). Allah forgives by covering sins so they aren't exposed on the Day of Judgment.",
        quranCount: 234,
        category: "Divine Attributes",
        derivations: [
            { arabic: "غَفَرَ", transliteration: "ghafara", meaning: "he forgave", form: "verb (past)", exampleVerse: "3:155" },
            { arabic: "يَغْفِرُ", transliteration: "yaghfiru", meaning: "he forgives", form: "verb (present)", exampleVerse: "39:53" },
            { arabic: "اِغْفِرْ", transliteration: "ighfir", meaning: "forgive!", form: "imperative", exampleVerse: "23:118" },
            { arabic: "غَفُور", transliteration: "Ghafur", meaning: "The Most Forgiving (divine name)", form: "intensive", exampleVerse: "2:173" },
            { arabic: "غَفَّار", transliteration: "Ghaffar", meaning: "The Continually Forgiving", form: "hyperbolic intensive", exampleVerse: "20:82" },
            { arabic: "مَغْفِرَة", transliteration: "maghfirah", meaning: "forgiveness", form: "verbal noun", exampleVerse: "2:221" },
            { arabic: "اسْتَغْفَرَ", transliteration: "istaghfara", meaning: "he sought forgiveness", form: "verb (form X)", exampleVerse: "71:10" },
        ],
    },
    {
        id: "kh-l-q",
        root: "خ ل ق",
        coreMeaning: "to create; character",
        explanation: "From this root: خَلْق (creation), الخَالِق (the Creator), and also خُلُق (character), because good character is seen as something 'created' and cultivated in a person.",
        quranCount: 261,
        category: "Divine Attributes",
        derivations: [
            { arabic: "خَلَقَ", transliteration: "khalaqa", meaning: "he created", form: "verb (past)", exampleVerse: "96:1" },
            { arabic: "يَخْلُقُ", transliteration: "yakhluqu", meaning: "he creates", form: "verb (present)", exampleVerse: "5:17" },
            { arabic: "خَلْق", transliteration: "khalq", meaning: "creation, creating", form: "verbal noun", exampleVerse: "31:11" },
            { arabic: "خَالِق", transliteration: "Khaliq", meaning: "Creator (divine name)", form: "active participle", exampleVerse: "59:24" },
            { arabic: "خَلَّاق", transliteration: "Khallaq", meaning: "The Perpetual Creator", form: "hyperbolic intensive", exampleVerse: "15:86" },
            { arabic: "مَخْلُوق", transliteration: "makhluq", meaning: "created thing, creature", form: "passive participle" },
            { arabic: "خُلُق", transliteration: "khuluq", meaning: "character, morals", form: "noun", exampleVerse: "68:4" },
        ],
    },
    {
        id: "r-z-q",
        root: "ر ز ق",
        coreMeaning: "to provide; provision",
        explanation: "Allah is الرَّزَّاق ('The Provider'). Rizq includes every provision, food, wealth, knowledge, family, health.",
        quranCount: 123,
        category: "Divine Attributes",
        derivations: [
            { arabic: "رَزَقَ", transliteration: "razaqa", meaning: "he provided", form: "verb (past)", exampleVerse: "2:57" },
            { arabic: "يَرْزُقُ", transliteration: "yarzuqu", meaning: "he provides", form: "verb (present)", exampleVerse: "3:27" },
            { arabic: "رِزْق", transliteration: "rizq", meaning: "provision, sustenance", form: "noun", exampleVerse: "2:3" },
            { arabic: "رَازِق", transliteration: "raziq", meaning: "provider", form: "active participle", exampleVerse: "5:114" },
            { arabic: "الرَّزَّاق", transliteration: "ar-Razzaq", meaning: "The Ever-Provider (divine name)", form: "hyperbolic intensive", exampleVerse: "51:58" },
            { arabic: "مَرْزُوق", transliteration: "marzuq", meaning: "one who is provided for", form: "passive participle" },
        ],
    },
    {
        id: "h-k-m",
        root: "ح ك م",
        coreMeaning: "to judge, to be wise",
        explanation: "Hukm means judgment, hikmah means wisdom. Allah is الحَكِيم (The All-Wise) and الحَكَم (The Judge).",
        quranCount: 210,
        category: "Divine Attributes",
        derivations: [
            { arabic: "حَكَمَ", transliteration: "hakama", meaning: "he judged", form: "verb (past)", exampleVerse: "5:45" },
            { arabic: "يَحْكُمُ", transliteration: "yahkumu", meaning: "he judges", form: "verb (present)", exampleVerse: "5:1" },
            { arabic: "حُكْم", transliteration: "hukm", meaning: "judgment, ruling", form: "noun", exampleVerse: "5:50" },
            { arabic: "حَكِيم", transliteration: "Hakim", meaning: "The All-Wise (divine name)", form: "intensive adjective", exampleVerse: "2:32" },
            { arabic: "حِكْمَة", transliteration: "hikmah", meaning: "wisdom", form: "noun", exampleVerse: "2:269" },
            { arabic: "حَاكِم", transliteration: "hakim", meaning: "judge, ruler", form: "active participle", exampleVerse: "95:8" },
            { arabic: "مُحْكَم", transliteration: "muhkam", meaning: "firmly established, decisive", form: "passive participle", exampleVerse: "3:7" },
        ],
    },

    // ─────────────────────────────────────────── CHARACTER ──
    {
        id: "a-m-n",
        root: "أ م ن",
        coreMeaning: "to be safe, to trust, to believe",
        explanation: "One of the most central roots in Islam. أَمَان = safety. اِيمَان = faith (because belief makes the heart secure). أَمِين = trustworthy. مُؤْمِن = believer. آمَنَ يُؤْمِنُ = he believed, he believes. The same root!",
        quranCount: 879,
        category: "Character",
        derivations: [
            { arabic: "آمَنَ", transliteration: "amana", meaning: "he believed / felt safe", form: "verb (form IV)", exampleVerse: "2:62" },
            { arabic: "يُؤْمِنُ", transliteration: "yu'minu", meaning: "he believes", form: "verb (present)", exampleVerse: "2:3" },
            { arabic: "إِيمَان", transliteration: "iman", meaning: "faith, belief", form: "verbal noun", exampleVerse: "49:7" },
            { arabic: "مُؤْمِن", transliteration: "mu'min", meaning: "believer", form: "active participle", exampleVerse: "2:8" },
            { arabic: "أَمِين", transliteration: "amin", meaning: "trustworthy", form: "intensive adjective", exampleVerse: "12:54" },
            { arabic: "أَمَانَة", transliteration: "amanah", meaning: "trust, covenant", form: "noun", exampleVerse: "33:72" },
            { arabic: "أَمْن", transliteration: "amn", meaning: "safety, security", form: "noun", exampleVerse: "3:97" },
            { arabic: "آمِين", transliteration: "amin", meaning: "ameen (may it be answered)", form: "particle", exampleVerse: "1:7" },
        ],
    },
    {
        id: "s-l-m",
        root: "س ل م",
        coreMeaning: "to be safe, to submit",
        explanation: "From one root come Islam (submission), Muslim (the submitter), salam (peace), and the greeting السلام عليكم. Islam literally means 'submission' and yields peace.",
        quranCount: 140,
        category: "Character",
        derivations: [
            { arabic: "سَلِمَ", transliteration: "salima", meaning: "he was safe", form: "verb (past)" },
            { arabic: "أَسْلَمَ", transliteration: "aslama", meaning: "he submitted / accepted Islam", form: "verb (form IV)", exampleVerse: "2:131" },
            { arabic: "إِسْلَام", transliteration: "Islam", meaning: "submission (to Allah)", form: "verbal noun", exampleVerse: "3:19" },
            { arabic: "مُسْلِم", transliteration: "Muslim", meaning: "one who submits", form: "active participle", exampleVerse: "3:102" },
            { arabic: "سَلَام", transliteration: "salam", meaning: "peace", form: "noun", exampleVerse: "36:58" },
            { arabic: "سَلَّمَ", transliteration: "sallama", meaning: "he greeted with peace", form: "verb (form II)", exampleVerse: "24:27" },
            { arabic: "سَلِيم", transliteration: "salim", meaning: "sound, untainted", form: "adjective", exampleVerse: "26:89" },
        ],
    },
    {
        id: "s-b-r",
        root: "ص ب ر",
        coreMeaning: "patience, endurance",
        explanation: "Sabr is mentioned over 90 times in the Quran. It means endurance in hardship, restraint in what is forbidden, and steadfastness in obedience, all at once.",
        quranCount: 102,
        category: "Character",
        derivations: [
            { arabic: "صَبَرَ", transliteration: "sabara", meaning: "he was patient", form: "verb (past)", exampleVerse: "2:175" },
            { arabic: "يَصْبِرُ", transliteration: "yasbiru", meaning: "he is patient", form: "verb (present)", exampleVerse: "12:90" },
            { arabic: "اِصْبِرْ", transliteration: "isbir", meaning: "be patient!", form: "imperative", exampleVerse: "10:109" },
            { arabic: "صَبْر", transliteration: "sabr", meaning: "patience", form: "verbal noun", exampleVerse: "2:45" },
            { arabic: "صَابِر", transliteration: "sabir", meaning: "patient person", form: "active participle", exampleVerse: "2:155" },
            { arabic: "صَبَّار", transliteration: "sabbar", meaning: "extremely patient", form: "hyperbolic intensive", exampleVerse: "14:5" },
        ],
    },
    {
        id: "sh-k-r",
        root: "ش ك ر",
        coreMeaning: "to thank, gratitude",
        explanation: "The Quranic counterpart to sabr. Allah promises: 'If you are grateful, I will surely increase you' (14:7). Shukur is thanks expressed with tongue, heart, and action.",
        quranCount: 75,
        category: "Character",
        derivations: [
            { arabic: "شَكَرَ", transliteration: "shakara", meaning: "he was grateful", form: "verb (past)", exampleVerse: "27:40" },
            { arabic: "يَشْكُرُ", transliteration: "yashkuru", meaning: "he is grateful", form: "verb (present)", exampleVerse: "27:40" },
            { arabic: "اشْكُرْ", transliteration: "ushkur", meaning: "be grateful!", form: "imperative", exampleVerse: "31:14" },
            { arabic: "شُكْر", transliteration: "shukr", meaning: "gratitude", form: "verbal noun", exampleVerse: "34:13" },
            { arabic: "شَاكِر", transliteration: "shakir", meaning: "grateful person", form: "active participle", exampleVerse: "76:3" },
            { arabic: "الشَّكُور", transliteration: "ash-Shakur", meaning: "The Most Appreciative (divine name)", form: "intensive", exampleVerse: "35:30" },
        ],
    },

    // ─────────────────────────────────────────── ACTION ──
    {
        id: "f-a-l",
        root: "ف ع ل",
        coreMeaning: "to do, to act",
        explanation: "Central to Arabic grammar itself, the verb is called فِعْل (the 'action word'). The root also gives ef'ala (forms of the verb) used in dictionaries.",
        quranCount: 108,
        category: "Action",
        derivations: [
            { arabic: "فَعَلَ", transliteration: "fa'ala", meaning: "he did", form: "verb (past)", exampleVerse: "2:24" },
            { arabic: "يَفْعَلُ", transliteration: "yaf'alu", meaning: "he does", form: "verb (present)", exampleVerse: "2:71" },
            { arabic: "اِفْعَلْ", transliteration: "if'al", meaning: "do!", form: "imperative", exampleVerse: "2:68" },
            { arabic: "فِعْل", transliteration: "fi'l", meaning: "action, deed; verb", form: "noun", exampleVerse: "11:111" },
            { arabic: "فَاعِل", transliteration: "fa'il", meaning: "doer, agent", form: "active participle", exampleVerse: "2:40" },
            { arabic: "مَفْعُول", transliteration: "maf'ul", meaning: "done, object of an action", form: "passive participle" },
        ],
    },
    {
        id: "a-m-l",
        root: "ع م ل",
        coreMeaning: "to work, to act righteously",
        explanation: "Amila is more specific than fa'ala, it usually implies sustained action or deeds, especially the righteous deeds mentioned everywhere with faith: 'those who believe and do righteous deeds (الصَّالِحَاتِ).'",
        quranCount: 359,
        category: "Action",
        derivations: [
            { arabic: "عَمِلَ", transliteration: "'amila", meaning: "he did, worked", form: "verb (past)", exampleVerse: "99:7" },
            { arabic: "يَعْمَلُ", transliteration: "ya'malu", meaning: "he works", form: "verb (present)", exampleVerse: "11:93" },
            { arabic: "اِعْمَلْ", transliteration: "i'mal", meaning: "act!", form: "imperative", exampleVerse: "34:11" },
            { arabic: "عَمَل", transliteration: "'amal", meaning: "deed, work", form: "noun", exampleVerse: "9:105" },
            { arabic: "عَامِل", transliteration: "'amil", meaning: "worker", form: "active participle", exampleVerse: "9:60" },
        ],
    },
    {
        id: "dh-h-b",
        root: "ذ ه ب",
        coreMeaning: "to go; gold",
        explanation: "Curiously, the same root means both 'to go' and 'gold'. The connection: gold is precious enough to 'go after'.",
        quranCount: 56,
        category: "Action",
        derivations: [
            { arabic: "ذَهَبَ", transliteration: "dhahaba", meaning: "he went", form: "verb (past)", exampleVerse: "2:108" },
            { arabic: "يَذْهَبُ", transliteration: "yadhhabu", meaning: "he goes", form: "verb (present)" },
            { arabic: "اِذْهَبْ", transliteration: "idhhab", meaning: "go!", form: "imperative", exampleVerse: "20:24" },
            { arabic: "ذَهَب", transliteration: "dhahab", meaning: "gold", form: "noun", exampleVerse: "9:34" },
        ],
    },

    // ─────────────────────────────────────────── PERCEPTION ──
    {
        id: "s-m-a",
        root: "س م ع",
        coreMeaning: "to hear, to listen",
        explanation: "Allah is السَّمِيع ('The All-Hearing'). The Quran repeatedly pairs 'hearing' with 'seeing' as the two windows through which humans receive knowledge.",
        quranCount: 185,
        category: "Perception",
        derivations: [
            { arabic: "سَمِعَ", transliteration: "sami'a", meaning: "he heard", form: "verb (past)", exampleVerse: "2:181" },
            { arabic: "يَسْمَعُ", transliteration: "yasma'u", meaning: "he hears", form: "verb (present)", exampleVerse: "2:20" },
            { arabic: "اسْمَعْ", transliteration: "isma'", meaning: "listen!", form: "imperative" },
            { arabic: "سَمْع", transliteration: "sam'", meaning: "hearing", form: "noun", exampleVerse: "6:46" },
            { arabic: "سَامِع", transliteration: "sami'", meaning: "hearer", form: "active participle", exampleVerse: "12:34" },
            { arabic: "سَمِيع", transliteration: "Sami'", meaning: "The All-Hearing (divine name)", form: "intensive", exampleVerse: "2:127" },
            { arabic: "اسْتَمَعَ", transliteration: "istama'a", meaning: "he listened attentively", form: "verb (form X)", exampleVerse: "72:1" },
        ],
    },
    {
        id: "b-s-r",
        root: "ب ص ر",
        coreMeaning: "to see, to have insight",
        explanation: "Not just physical sight, bismah is inner insight too. Allah is البَصِير ('The All-Seeing'). بَصِيرَة = insight.",
        quranCount: 148,
        category: "Perception",
        derivations: [
            { arabic: "أَبْصَرَ", transliteration: "absara", meaning: "he saw", form: "verb (form IV)", exampleVerse: "12:96" },
            { arabic: "يُبْصِرُ", transliteration: "yubsiru", meaning: "he sees", form: "verb (present)", exampleVerse: "7:179" },
            { arabic: "بَصَر", transliteration: "basar", meaning: "sight, vision", form: "noun", exampleVerse: "24:43" },
            { arabic: "بَصِير", transliteration: "Basir", meaning: "The All-Seeing (divine name)", form: "intensive", exampleVerse: "2:96" },
            { arabic: "بَصِيرَة", transliteration: "basirah", meaning: "insight", form: "noun", exampleVerse: "12:108" },
            { arabic: "مُبْصِر", transliteration: "mubsir", meaning: "one who sees, visible", form: "active participle", exampleVerse: "27:13" },
        ],
    },
    {
        id: "r-a-y",
        root: "ر أ ي",
        coreMeaning: "to see, to think, to consider",
        explanation: "Covers both physical sight ('he saw the moon') and mental consideration ('he thought, he had an opinion'). The same root yields رُؤْيَا, a dream-vision.",
        quranCount: 328,
        category: "Perception",
        derivations: [
            { arabic: "رَأَى", transliteration: "ra'a", meaning: "he saw", form: "verb (past)", exampleVerse: "6:76" },
            { arabic: "يَرَى", transliteration: "yara", meaning: "he sees", form: "verb (present)", exampleVerse: "99:7" },
            { arabic: "رَأْي", transliteration: "ra'y", meaning: "opinion", form: "noun" },
            { arabic: "رُؤْيَا", transliteration: "ru'ya", meaning: "vision, dream", form: "noun", exampleVerse: "12:4" },
            { arabic: "أَرَى", transliteration: "ara", meaning: "he showed", form: "verb (form IV)", exampleVerse: "2:260" },
            { arabic: "مَرْأَى", transliteration: "mar'a", meaning: "something seen, a sight", form: "noun of place" },
        ],
    },

    // ─────────────────────────────────────────── BODY & SELF ──
    {
        id: "q-l-b",
        root: "ق ل ب",
        coreMeaning: "heart; to turn, to overturn",
        explanation: "The Arabic word for 'heart' comes from the root meaning 'to turn', because the heart constantly flips between states. The Prophet ﷺ used to pray: 'O Turner of hearts, keep my heart firm on Your religion.'",
        quranCount: 168,
        category: "Body & Self",
        derivations: [
            { arabic: "قَلَبَ", transliteration: "qalaba", meaning: "he turned, flipped", form: "verb (past)", exampleVerse: "18:42" },
            { arabic: "قَلْب", transliteration: "qalb", meaning: "heart", form: "noun", exampleVerse: "50:37" },
            { arabic: "قُلُوب", transliteration: "qulub", meaning: "hearts (plural)", form: "noun (plural)", exampleVerse: "13:28" },
            { arabic: "اِنْقَلَبَ", transliteration: "inqalaba", meaning: "he turned back, reverted", form: "verb (form VII)", exampleVerse: "3:144" },
            { arabic: "مُنْقَلَب", transliteration: "munqalab", meaning: "return, final destination", form: "noun of place", exampleVerse: "18:36" },
            { arabic: "مُقَلِّب", transliteration: "muqallib", meaning: "the One who turns (hearts)", form: "active participle" },
        ],
    },
    {
        id: "n-f-s",
        root: "ن ف س",
        coreMeaning: "soul, self, breath",
        explanation: "Nafs refers both to the soul and to the self. In Quranic psychology, there are three types: commanding (to evil), self-reproaching, and tranquil.",
        quranCount: 298,
        category: "Body & Self",
        derivations: [
            { arabic: "نَفْس", transliteration: "nafs", meaning: "soul, self, person", form: "noun", exampleVerse: "91:7" },
            { arabic: "أَنْفُس", transliteration: "anfus", meaning: "selves, souls (plural)", form: "noun (plural)", exampleVerse: "2:54" },
            { arabic: "تَنَفَّسَ", transliteration: "tanaffasa", meaning: "he breathed", form: "verb (form V)", exampleVerse: "81:18" },
            { arabic: "نَفَس", transliteration: "nafas", meaning: "breath", form: "noun" },
            { arabic: "نَفِيس", transliteration: "nafis", meaning: "precious, valuable", form: "adjective" },
        ],
    },
    {
        id: "r-w-h",
        root: "ر و ح",
        coreMeaning: "spirit, soul; wind",
        explanation: "Ruh is the pure spirit breathed into humans by Allah (15:29). The archangel Jibril is called الرُّوح ('the Spirit'). Rih (same root, slightly different vowels) means wind, also invisible, also sent by Allah.",
        quranCount: 57,
        category: "Body & Self",
        derivations: [
            { arabic: "رُوح", transliteration: "ruh", meaning: "spirit, soul", form: "noun", exampleVerse: "17:85" },
            { arabic: "رِيح", transliteration: "rih", meaning: "wind", form: "noun", exampleVerse: "15:22" },
            { arabic: "رِيَاح", transliteration: "riyah", meaning: "winds (plural)", form: "noun (plural)", exampleVerse: "7:57" },
            { arabic: "رَيْحَان", transliteration: "rayhan", meaning: "fragrant plant", form: "noun", exampleVerse: "55:12" },
            { arabic: "أَرَاحَ", transliteration: "araha", meaning: "he gave rest", form: "verb (form IV)" },
        ],
    },

    // ─────────────────────────────────────────── CREATION ──
    {
        id: "n-w-r",
        root: "ن و ر",
        coreMeaning: "light; fire",
        explanation: "Allah is النُّور (The Light). The same root gives نَار (fire), the idea that fire is 'visible light' vs. the hidden Light of Allah. Surah An-Nur (24) is named for this.",
        quranCount: 194,
        category: "Creation",
        derivations: [
            { arabic: "نُور", transliteration: "nur", meaning: "light", form: "noun", exampleVerse: "24:35" },
            { arabic: "نَار", transliteration: "nar", meaning: "fire", form: "noun", exampleVerse: "2:24" },
            { arabic: "أَنْوَار", transliteration: "anwar", meaning: "lights (plural)", form: "noun (plural)" },
            { arabic: "مُنِير", transliteration: "munir", meaning: "illuminating", form: "active participle", exampleVerse: "33:46" },
            { arabic: "اسْتَنَارَ", transliteration: "istanara", meaning: "he sought light", form: "verb (form X)" },
        ],
    },
    {
        id: "h-d-y",
        root: "ه د ي",
        coreMeaning: "to guide, guidance",
        explanation: "The most frequent word for 'guidance' in the Quran. The sacrificial animal in Hajj is called هَدْي from the same root, it's 'led' to the sanctuary.",
        quranCount: 316,
        category: "Creation",
        derivations: [
            { arabic: "هَدَى", transliteration: "hada", meaning: "he guided", form: "verb (past)", exampleVerse: "7:30" },
            { arabic: "يَهْدِي", transliteration: "yahdi", meaning: "he guides", form: "verb (present)", exampleVerse: "2:213" },
            { arabic: "اِهْدِ", transliteration: "ihdi", meaning: "guide!", form: "imperative", exampleVerse: "1:6" },
            { arabic: "هُدَى", transliteration: "huda", meaning: "guidance", form: "verbal noun", exampleVerse: "2:2" },
            { arabic: "هَادِي", transliteration: "hadi", meaning: "guide", form: "active participle", exampleVerse: "22:54" },
            { arabic: "مُهْتَدِي", transliteration: "muhtadi", meaning: "rightly-guided", form: "active participle (form VIII)", exampleVerse: "2:70" },
        ],
    },
];
