// Searchable Islamic glossary. ~120 terms covering worship, theology, fiqh, ethics, seerah, and day-to-day vocabulary.
// Each term: transliteration, Arabic, category, short definition.
// Portable pure-data module, no React deps.

export type GlossaryCategory =
    | "Pillars & Worship"
    | "Theology"
    | "Quran & Revelation"
    | "Ethics & Character"
    | "Jurisprudence"
    | "Eschatology"
    | "Prayer & Rites"
    | "Community & Society"
    | "Daily Practice"
    | "Seerah & History";

export interface GlossaryTerm {
    id: string;            // slug: "taqwa" etc
    term: string;          // transliteration, e.g. "Taqwa"
    arabic: string;        // Arabic, e.g. "تَقْوَى"
    plural?: string;       // plural form if relevant
    category: GlossaryCategory;
    definition: string;    // 1-3 sentences
    relatedTerms?: string[]; // ids of related entries
}

export const GLOSSARY: GlossaryTerm[] = [
    // --- Pillars & Worship ---
    { id: "shahada", term: "Shahadah", arabic: "الشَّهَادَة", category: "Pillars & Worship", definition: "The declaration of faith: 'La ilaha illa Allah, Muhammadur Rasulullah', 'There is no god but Allah, and Muhammad is the Messenger of Allah.' The first and foundational pillar of Islam.", relatedTerms: ["iman", "tawhid"] },
    { id: "salah", term: "Salah", arabic: "الصَّلَاة", plural: "Salawat", category: "Pillars & Worship", definition: "The five daily prescribed prayers (Fajr, Dhuhr, 'Asr, Maghrib, 'Isha). The second pillar of Islam and the direct link between a believer and Allah.", relatedTerms: ["wudu", "qibla", "adhan"] },
    { id: "zakat", term: "Zakat", arabic: "الزَّكَاة", category: "Pillars & Worship", definition: "Obligatory alms, 2.5% of one's wealth above the nisab threshold, given annually to the poor, needy, and other specified categories. The third pillar of Islam.", relatedTerms: ["sadaqah", "nisab"] },
    { id: "sawm", term: "Sawm", arabic: "الصَّوْم", category: "Pillars & Worship", definition: "Fasting, abstaining from food, drink, and marital relations from dawn (fajr) to sunset (maghrib). Obligatory during the month of Ramadan; the fourth pillar of Islam.", relatedTerms: ["ramadan", "iftar", "suhur"] },
    { id: "hajj", term: "Hajj", arabic: "الحَجّ", category: "Pillars & Worship", definition: "Pilgrimage to Mecca, obligatory once in a lifetime on every able Muslim who can afford it. Performed in Dhul Hijjah; the fifth pillar of Islam.", relatedTerms: ["umrah", "ihram", "kaaba"] },
    { id: "umrah", term: "'Umrah", arabic: "العُمْرَة", category: "Pillars & Worship", definition: "The 'lesser pilgrimage', performed at any time of year, consisting of ihram, tawaf, sa'i, and halq/taqsir. Highly recommended but not obligatory.", relatedTerms: ["hajj", "tawaf", "sai"] },

    // --- Theology ---
    { id: "tawhid", term: "Tawhid", arabic: "التَّوْحِيد", category: "Theology", definition: "The absolute oneness of Allah, the heart of Islamic belief. He is One, without partner, without equal, self-subsisting, unlike any of His creation.", relatedTerms: ["shirk", "iman"] },
    { id: "iman", term: "Iman", arabic: "الإِيمَان", category: "Theology", definition: "Faith, belief in Allah, His angels, His books, His messengers, the Last Day, and divine decree (qadar). Iman is expressed by the tongue, confirmed by the heart, and acted upon by the limbs.", relatedTerms: ["islam", "ihsan"] },
    { id: "islam", term: "Islam", arabic: "الإِسْلَام", category: "Theology", definition: "'Submission', the religion of complete surrender to the will of Allah. Also a state: the outward practice (five pillars) as distinct from iman (inward faith) and ihsan (excellence).", relatedTerms: ["iman", "ihsan"] },
    { id: "ihsan", term: "Ihsan", arabic: "الإِحْسَان", category: "Theology", definition: "Spiritual excellence, defined by the Prophet ﷺ as 'to worship Allah as though you see Him; and if you do not see Him, then know that He sees you.' The highest spiritual station.", relatedTerms: ["islam", "iman"] },
    { id: "shirk", term: "Shirk", arabic: "الشِّرْك", category: "Theology", definition: "Associating partners with Allah, the only sin the Quran says Allah will not forgive if one dies upon it. Opposite of tawhid.", relatedTerms: ["tawhid", "kufr"] },
    { id: "kufr", term: "Kufr", arabic: "الكُفْر", category: "Theology", definition: "Disbelief, literally 'covering' the truth. The rejection of Allah, His messengers, or what they have brought.", relatedTerms: ["iman", "shirk"] },
    { id: "nifaq", term: "Nifaq", arabic: "النِّفَاق", category: "Theology", definition: "Hypocrisy, outward profession of Islam while inwardly disbelieving. Described in the Quran as worse than open disbelief.", relatedTerms: ["kufr", "munafiq"] },
    { id: "munafiq", term: "Munafiq", arabic: "مُنَافِق", plural: "Munafiqun", category: "Theology", definition: "A hypocrite, one who professes Islam outwardly but disbelieves inwardly. Surah Al-Munafiqun addresses them directly.", relatedTerms: ["nifaq"] },
    { id: "allah", term: "Allah", arabic: "ٱللّٰه", category: "Theology", definition: "The proper name of the One God, the Creator, the Sustainer, the Sovereign. The Arabic word used by Arab Christians and Jews for God for centuries before and after the Quran.", relatedTerms: ["tawhid", "asma-ul-husna"] },
    { id: "asma-ul-husna", term: "Al-Asma al-Husna", arabic: "الأَسْمَاء الحُسْنَى", category: "Theology", definition: "'The Most Beautiful Names' of Allah, 99 names describing His attributes (Ar-Rahman, Ar-Rahim, Al-Malik, Al-Quddus, etc). Memorizing and contemplating them is a recommended act of worship.", relatedTerms: ["allah"] },
    { id: "qadar", term: "Qadar", arabic: "القَدَر", category: "Theology", definition: "Divine decree, the belief that Allah has willed and known everything that will happen. The sixth article of iman.", relatedTerms: ["iman"] },
    { id: "malaika", term: "Mala'ikah", arabic: "المَلَائِكَة", category: "Theology", definition: "Angels, created from light, sinless, obedient to Allah. Belief in them is an article of iman. Notable angels: Jibril (Gabriel), Mika'il (Michael), Israfil, Malak al-Mawt.", relatedTerms: ["jibril", "iman"] },
    { id: "jibril", term: "Jibril", arabic: "جِبْرِيل", category: "Theology", definition: "The archangel Gabriel, the angel of revelation, who brought the Quran to the Prophet Muhammad ﷺ and scripture to the prophets before him.", relatedTerms: ["malaika", "wahy"] },
    { id: "jinn", term: "Jinn", arabic: "الجِنّ", category: "Theology", definition: "A class of created beings made from smokeless fire, possessing free will like humans. Some are Muslim, some are not. Iblis (Shaytan) is from the jinn.", relatedTerms: ["iblis"] },
    { id: "iblis", term: "Iblis / Shaytan", arabic: "إِبْلِيس / الشَّيْطَان", category: "Theology", definition: "Iblis, the jinn who refused to prostrate to Adam and was cast out. Shaytan (Satan) is his title as the constant whisperer against humankind. His enmity is ancient and explicit.", relatedTerms: ["jinn"] },

    // --- Quran & Revelation ---
    { id: "quran", term: "Quran", arabic: "القُرْآن", category: "Quran & Revelation", definition: "'The Recitation', the final scripture, revealed to Prophet Muhammad ﷺ through Jibril over 23 years (610-632 CE). The literal word of Allah, preserved in Arabic.", relatedTerms: ["wahy", "surah", "ayah"] },
    { id: "surah", term: "Surah", arabic: "سُورَة", plural: "Suwar", category: "Quran & Revelation", definition: "A chapter of the Quran. There are 114 surahs, varying from 3 to 286 verses. Classified as Makki (revealed in Mecca) or Madani (revealed in Medina).", relatedTerms: ["ayah", "juz"] },
    { id: "ayah", term: "Ayah", arabic: "آيَة", plural: "Ayat", category: "Quran & Revelation", definition: "A verse of the Quran, also the Arabic word for 'sign.' The Quran has 6,236 ayat.", relatedTerms: ["surah"] },
    { id: "juz", term: "Juz'", arabic: "جُزْء", plural: "Ajza", category: "Quran & Revelation", definition: "One of 30 roughly equal sections the Quran is divided into for easier reading, especially during Ramadan, when many complete a juz per day.", relatedTerms: ["hizb", "surah"] },
    { id: "hizb", term: "Hizb", arabic: "حِزْب", category: "Quran & Revelation", definition: "Half of a juz. The Quran contains 60 hizbs. Often used for reading schedules.", relatedTerms: ["juz"] },
    { id: "wahy", term: "Wahy", arabic: "الوَحْي", category: "Quran & Revelation", definition: "Revelation, the divine communication from Allah to a prophet, whether through the angel, a true dream, or direct speech (as with Musa).", relatedTerms: ["quran", "jibril"] },
    { id: "tafsir", term: "Tafsir", arabic: "التَّفْسِير", category: "Quran & Revelation", definition: "Exegesis, the explanation and interpretation of the Quran. Classical tafasir include Ibn Kathir, At-Tabari, and Al-Qurtubi.", relatedTerms: ["quran", "tajwid"] },
    { id: "tajwid", term: "Tajwid", arabic: "التَّجْوِيد", category: "Quran & Revelation", definition: "The rules of proper Quranic recitation, how each letter is pronounced, where to pause, how to elongate vowels. Derived from 'jayyid' (good).", relatedTerms: ["quran", "qari"] },
    { id: "hifdh", term: "Hifdh", arabic: "الحِفْظ", category: "Quran & Revelation", definition: "Memorization of the Quran. One who has memorized the entire Quran is called a hafiz (or hafidh). A Qur'an-by-heart tradition spanning 1,400 years.", relatedTerms: ["hafiz", "quran"] },
    { id: "hafiz", term: "Hafiz", arabic: "حَافِظ", plural: "Huffadh", category: "Quran & Revelation", definition: "One who has memorized the entire Quran by heart. A living chain of preservation since the Prophet ﷺ.", relatedTerms: ["hifdh"] },
    { id: "qari", term: "Qari'", arabic: "قَارِئ", plural: "Qurra", category: "Quran & Revelation", definition: "A reciter of the Quran, especially one trained in a specific qira'ah (recitation style) with tajwid.", relatedTerms: ["tajwid", "qiraat"] },
    { id: "qiraat", term: "Qira'at", arabic: "القِرَاءَات", category: "Quran & Revelation", definition: "The canonical readings of the Quran, 10 (or 7) authenticated recitation traditions, all traced back to the Prophet ﷺ. Hafs and Warsh are the most widely read today.", relatedTerms: ["qari"] },
    { id: "bismillah", term: "Bismillah", arabic: "بِسْمِ اللَّه", category: "Quran & Revelation", definition: "'In the name of Allah', shorthand for Bismillahir-Rahmanir-Rahim, the opening phrase of 113 of the 114 surahs of the Quran, and the recommended opening of every act.", relatedTerms: ["quran"] },
    { id: "fatiha", term: "Al-Fatiha", arabic: "الفَاتِحَة", category: "Quran & Revelation", definition: "'The Opener', the first surah of the Quran, recited in every raka'ah of every prayer. Also called Umm al-Kitab ('Mother of the Book') and As-Sab' al-Mathani ('The Seven Oft-Repeated').", relatedTerms: ["salah", "surah"] },
    { id: "hadith", term: "Hadith", arabic: "الحَدِيث", plural: "Ahadith", category: "Quran & Revelation", definition: "A report of the sayings, actions, or tacit approvals of the Prophet Muhammad ﷺ. Compiled in collections such as Sahih al-Bukhari and Sahih Muslim.", relatedTerms: ["sunnah", "isnad"] },
    { id: "sunnah", term: "Sunnah", arabic: "السُّنَّة", category: "Quran & Revelation", definition: "The example of the Prophet Muhammad ﷺ, his sayings, actions, and approvals. The second source of Islamic law after the Quran.", relatedTerms: ["hadith"] },
    { id: "isnad", term: "Isnad", arabic: "الإِسْنَاد", category: "Quran & Revelation", definition: "The chain of narrators for a hadith, tracing it back to the Prophet ﷺ. The isnad's authenticity determines whether a hadith is sahih (authentic), hasan (good), or da'if (weak).", relatedTerms: ["hadith"] },

    // --- Prayer & Rites ---
    { id: "wudu", term: "Wudu", arabic: "الوُضُوء", category: "Prayer & Rites", definition: "Ritual ablution before prayer, washing hands, rinsing the mouth and nose, washing the face, arms to the elbows, wiping the head, and washing the feet to the ankles.", relatedTerms: ["salah", "ghusl"] },
    { id: "ghusl", term: "Ghusl", arabic: "الغُسْل", category: "Prayer & Rites", definition: "Full ritual bath, required after major impurity (janabah), after menses, and recommended for Jumu'ah and 'Id.", relatedTerms: ["wudu"] },
    { id: "tayammum", term: "Tayammum", arabic: "التَّيَمُّم", category: "Prayer & Rites", definition: "Dry ablution using clean earth, permitted when water is unavailable or harmful to health. Strikes the ground and wipes face and hands.", relatedTerms: ["wudu"] },
    { id: "adhan", term: "Adhan", arabic: "الأَذَان", category: "Prayer & Rites", definition: "The call to prayer, announced five times a day from the mosque. Bilal ibn Rabah was the first muezzin of Islam.", relatedTerms: ["iqama", "salah"] },
    { id: "iqama", term: "Iqamah", arabic: "الإِقَامَة", category: "Prayer & Rites", definition: "The second call, given immediately before the prayer begins in the mosque. A shortened form of the adhan.", relatedTerms: ["adhan", "salah"] },
    { id: "qibla", term: "Qiblah", arabic: "القِبْلَة", category: "Prayer & Rites", definition: "The direction of prayer, facing the Ka'bah in Mecca. Changed from Jerusalem to the Ka'bah in 2 AH.", relatedTerms: ["kaaba", "salah"] },
    { id: "kaaba", term: "Ka'bah", arabic: "الكَعْبَة", category: "Prayer & Rites", definition: "The cube-shaped house of worship in Mecca, built by Ibrahim and Isma'il on the foundation laid by Adam. The qiblah of all Muslims and the center of Hajj and 'Umrah.", relatedTerms: ["qibla", "hajj"] },
    { id: "raka", term: "Rak'ah", arabic: "رَكْعَة", plural: "Raka'at", category: "Prayer & Rites", definition: "A unit of prayer, comprising standing, bowing (ruku'), prostration (sujud), and sitting. Fajr is 2 raka'at, Dhuhr/'Asr/'Isha are 4, Maghrib is 3.", relatedTerms: ["salah", "sujud"] },
    { id: "ruku", term: "Ruku'", arabic: "الرُّكُوع", category: "Prayer & Rites", definition: "The bowing position in prayer, with hands on knees and back straight. 'Subhana Rabbiyal 'Adhim' is recited.", relatedTerms: ["raka", "salah"] },
    { id: "sujud", term: "Sujud", arabic: "السُّجُود", category: "Prayer & Rites", definition: "Prostration, the position closest to Allah, with forehead, nose, palms, knees, and toes on the ground. 'Subhana Rabbiyal A'la' is recited.", relatedTerms: ["salah", "raka"] },
    { id: "tashahhud", term: "Tashahhud", arabic: "التَّشَهُّد", category: "Prayer & Rites", definition: "The testimony of faith recited while seated after the second and final rak'ah. 'At-tahiyyatu lillahi...'", relatedTerms: ["salah", "shahada"] },
    { id: "tasleem", term: "Taslim", arabic: "التَّسْلِيم", category: "Prayer & Rites", definition: "The greeting of peace that ends the prayer, 'As-salamu 'alaykum wa rahmatullah' turned to the right then the left.", relatedTerms: ["salah"] },
    { id: "witr", term: "Witr", arabic: "الوِتْر", category: "Prayer & Rites", definition: "The odd-numbered night prayer, prayed after 'Isha and before Fajr, usually 1, 3, 5, or more raka'at. Strongly emphasized sunnah.", relatedTerms: ["tahajjud", "salah"] },
    { id: "tahajjud", term: "Tahajjud", arabic: "التَّهَجُّد", category: "Prayer & Rites", definition: "The voluntary night prayer, prayed after sleeping and before Fajr. One of the most beloved voluntary worships.", relatedTerms: ["witr", "qiyam"] },
    { id: "qiyam", term: "Qiyam al-Layl", arabic: "قِيَام اللَّيْل", category: "Prayer & Rites", definition: "Standing in night prayer, any voluntary prayer observed during the night, including tahajjud.", relatedTerms: ["tahajjud"] },
    { id: "taraweeh", term: "Taraweeh", arabic: "التَّرَاوِيح", category: "Prayer & Rites", definition: "Special night prayers offered in congregation during Ramadan, typically 8 or 20 raka'at, in which a hafiz often recites the entire Quran over the month.", relatedTerms: ["ramadan", "qiyam"] },
    { id: "jumuah", term: "Jumu'ah", arabic: "الجُمُعَة", category: "Prayer & Rites", definition: "Friday, and the obligatory congregational Friday prayer, which replaces Dhuhr for men. Includes a khutbah (sermon) before the prayer.", relatedTerms: ["khutbah", "salah"] },
    { id: "khutbah", term: "Khutbah", arabic: "الخُطْبَة", category: "Prayer & Rites", definition: "A sermon, delivered before Jumu'ah prayer, at 'Id, and at marriages. A condition of the validity of Jumu'ah.", relatedTerms: ["jumuah"] },
    { id: "janazah", term: "Salat al-Janazah", arabic: "صَلَاة الجَنَازَة", category: "Prayer & Rites", definition: "The funeral prayer, offered for a deceased Muslim before burial. Four takbirs, no ruku' or sujud.", relatedTerms: ["salah"] },

    // --- Rites of Hajj ---
    { id: "ihram", term: "Ihram", arabic: "الإِحْرَام", category: "Prayer & Rites", definition: "The sacred state entered before Hajj or 'Umrah, marked by two unstitched white garments for men, and by specific restrictions (no perfume, no hunting, no marital relations) for all.", relatedTerms: ["hajj", "umrah"] },
    { id: "tawaf", term: "Tawaf", arabic: "الطَّوَاف", category: "Prayer & Rites", definition: "Circumambulation of the Ka'bah seven times counter-clockwise, starting from the Black Stone. A central rite of Hajj and 'Umrah.", relatedTerms: ["hajj", "umrah", "kaaba"] },
    { id: "sai", term: "Sa'i", arabic: "السَّعْي", category: "Prayer & Rites", definition: "Walking between the hills of Safa and Marwah seven times, commemorating Hajar's search for water for her son Isma'il.", relatedTerms: ["hajj", "umrah"] },
    { id: "wuquf", term: "Wuquf at 'Arafah", arabic: "الوُقُوف بِعَرَفَة", category: "Prayer & Rites", definition: "Standing at the plain of 'Arafah on the 9th of Dhul Hijjah, the central pillar of Hajj. 'Hajj is 'Arafah.'", relatedTerms: ["hajj"] },
    { id: "mina", term: "Mina", arabic: "مِنَى", category: "Prayer & Rites", definition: "A valley near Mecca where pilgrims camp during the days of Hajj and perform the stoning of the jamarat.", relatedTerms: ["hajj", "jamarat"] },
    { id: "muzdalifah", term: "Muzdalifah", arabic: "مُزْدَلِفَة", category: "Prayer & Rites", definition: "An open plain between 'Arafah and Mina where pilgrims spend the night after 'Arafah, collecting pebbles for stoning the jamarat.", relatedTerms: ["hajj", "jamarat"] },
    { id: "jamarat", term: "Jamarat", arabic: "الجَمَرَات", category: "Prayer & Rites", definition: "Three stone pillars at Mina representing the places where Shaytan attempted to dissuade Ibrahim. Pilgrims symbolically stone them during Hajj.", relatedTerms: ["hajj", "mina"] },
    { id: "qurbani", term: "Qurbani / Udhiyah", arabic: "الأُضْحِيَة", category: "Prayer & Rites", definition: "The sacrifice of a sheep, goat, cow, or camel on the Day of 'Id al-Adha, commemorating Ibrahim's willingness to sacrifice Isma'il.", relatedTerms: ["eid-adha", "hajj"] },
    { id: "talbiyah", term: "Talbiyah", arabic: "التَّلْبِيَة", category: "Prayer & Rites", definition: "The Hajj chant: 'Labbayk Allahumma Labbayk, Labbayka la sharika laka labbayk...' ('Here I am, O Allah, here I am...'). Recited constantly during Hajj.", relatedTerms: ["hajj", "ihram"] },
    { id: "halq", term: "Halq / Taqsir", arabic: "الحَلْق / التَّقْصِير", category: "Prayer & Rites", definition: "Shaving (halq) or trimming (taqsir) the hair after Hajj or 'Umrah, marking the end of the state of ihram.", relatedTerms: ["hajj", "umrah"] },
    { id: "zamzam", term: "Zamzam", arabic: "زَمْزَم", category: "Prayer & Rites", definition: "The miraculous spring in Mecca that gushed forth for Hajar and baby Isma'il. Pilgrims drink from it during Hajj and 'Umrah.", relatedTerms: ["hajj", "umrah"] },

    // --- Fasting & Ramadan ---
    { id: "ramadan", term: "Ramadan", arabic: "رَمَضَان", category: "Daily Practice", definition: "The ninth month of the Islamic calendar, the month in which the Quran was first revealed and in which fasting is obligatory on all able Muslims.", relatedTerms: ["sawm", "lailatul-qadr", "iftar"] },
    { id: "iftar", term: "Iftar", arabic: "الإِفْطَار", category: "Daily Practice", definition: "Breaking the fast at sunset during Ramadan, sunnah to open with dates and water, followed by the maghrib prayer.", relatedTerms: ["sawm", "ramadan", "suhur"] },
    { id: "suhur", term: "Suhur", arabic: "السُّحُور", category: "Daily Practice", definition: "The pre-dawn meal eaten before the fast begins. The Prophet ﷺ said: 'There is blessing in suhur.'", relatedTerms: ["sawm", "iftar"] },
    { id: "lailatul-qadr", term: "Laylat al-Qadr", arabic: "لَيْلَة القَدْر", category: "Daily Practice", definition: "'The Night of Decree', one of the odd last ten nights of Ramadan (commonly sought on the 27th). 'Better than a thousand months' (97:3).", relatedTerms: ["ramadan"] },
    { id: "itikaf", term: "I'tikaf", arabic: "الاعْتِكَاف", category: "Daily Practice", definition: "Spiritual retreat in the mosque, often during the last ten nights of Ramadan, devoted to worship, Quran, and du'a.", relatedTerms: ["ramadan", "lailatul-qadr"] },
    { id: "eid-fitr", term: "'Id al-Fitr", arabic: "عِيد الفِطْر", category: "Daily Practice", definition: "'Festival of Breaking the Fast', the first of the two 'Ids, celebrated on the 1st of Shawwal immediately after Ramadan. Begins with 'Id prayer.", relatedTerms: ["ramadan", "zakat-fitr"] },
    { id: "eid-adha", term: "'Id al-Adha", arabic: "عِيد الأَضْحَى", category: "Daily Practice", definition: "'Festival of the Sacrifice', the second 'Id, celebrated on the 10th of Dhul Hijjah. Commemorates Ibrahim's sacrifice; marked by qurbani (animal sacrifice).", relatedTerms: ["hajj", "qurbani"] },
    { id: "zakat-fitr", term: "Zakat al-Fitr", arabic: "زَكَاة الفِطْر", category: "Daily Practice", definition: "A small obligatory charity (one sa' of staple food or its value) given before 'Id al-Fitr prayer by every Muslim who has food beyond their family's needs.", relatedTerms: ["zakat", "eid-fitr"] },

    // --- Ethics & Character ---
    { id: "taqwa", term: "Taqwa", arabic: "التَّقْوَى", category: "Ethics & Character", definition: "God-consciousness, awareness of Allah that protects one from what displeases Him. Often translated as 'piety' or 'mindfulness.' The Quran's criterion for nobility: 'the noblest of you is the most taqwa.'", relatedTerms: ["iman", "ihsan"] },
    { id: "sabr", term: "Sabr", arabic: "الصَّبْر", category: "Ethics & Character", definition: "Patience, endurance in hardship, steadfastness in obedience, and restraint from what is forbidden. Mentioned over 90 times in the Quran.", relatedTerms: ["shukr"] },
    { id: "shukr", term: "Shukr", arabic: "الشُّكْر", category: "Ethics & Character", definition: "Gratitude, recognition and verbal/active thanks for blessings. Allah promises: 'If you are grateful, I will surely increase you' (14:7).", relatedTerms: ["sabr"] },
    { id: "tawba", term: "Tawbah", arabic: "التَّوْبَة", category: "Ethics & Character", definition: "Repentance, sincere return to Allah with regret, cessation of the sin, and resolve not to return. Allah loves those who repent (2:222).", relatedTerms: ["istighfar"] },
    { id: "istighfar", term: "Istighfar", arabic: "الاسْتِغْفَار", category: "Ethics & Character", definition: "Seeking Allah's forgiveness, 'Astaghfirullah.' A hallmark of the pious; the Prophet ﷺ said it 70-100 times a day.", relatedTerms: ["tawba"] },
    { id: "ikhlas", term: "Ikhlas", arabic: "الإِخْلَاص", category: "Ethics & Character", definition: "Sincerity, doing every act solely for the sake of Allah, with no share for anyone or anything else.", relatedTerms: ["riya"] },
    { id: "riya", term: "Riya", arabic: "الرِّيَاء", category: "Ethics & Character", definition: "Showing off, performing acts of worship to be seen by people. Called 'the minor shirk' by the Prophet ﷺ.", relatedTerms: ["ikhlas"] },
    { id: "tawakkul", term: "Tawakkul", arabic: "التَّوَكُّل", category: "Ethics & Character", definition: "Reliance on Allah, doing what is in one's power and leaving the outcome to Him. 'Tie your camel, then trust in Allah.'", relatedTerms: ["iman"] },
    { id: "khushu", term: "Khushu'", arabic: "الخُشُوع", category: "Ethics & Character", definition: "Humble presence, stillness of body and heart in worship, especially in salah. The quality that defines the successful believers (23:1-2).", relatedTerms: ["salah"] },
    { id: "rahma", term: "Rahmah", arabic: "الرَّحْمَة", category: "Ethics & Character", definition: "Mercy, compassion toward creation. Allah named Himself Ar-Rahman and Ar-Rahim from this root; the Prophet ﷺ is 'a mercy to the worlds' (21:107).", relatedTerms: ["allah"] },
    { id: "adab", term: "Adab", arabic: "الأَدَب", category: "Ethics & Character", definition: "Etiquette, refinement, respect, the correct manner of speaking, eating, greeting, learning, and conducting oneself.", relatedTerms: ["akhlaq"] },
    { id: "akhlaq", term: "Akhlaq", arabic: "الأَخْلَاق", category: "Ethics & Character", definition: "Moral character, the deepest quality of the Muslim. The Prophet ﷺ said: 'I was sent only to perfect noble character.'", relatedTerms: ["adab"] },
    { id: "barakah", term: "Barakah", arabic: "البَرَكَة", category: "Ethics & Character", definition: "Blessing, divine favor that multiplies and sustains the benefit in a thing, whether time, wealth, food, or knowledge.", relatedTerms: ["rizq"] },
    { id: "rizq", term: "Rizq", arabic: "الرِّزْق", category: "Ethics & Character", definition: "Provision, everything Allah has allotted to a person (food, wealth, knowledge, family). Allah is Ar-Razzaq, the Provider.", relatedTerms: ["barakah"] },

    // --- Jurisprudence ---
    { id: "halal", term: "Halal", arabic: "حَلَال", category: "Jurisprudence", definition: "Permissible, lawful, allowed by the shari'ah. The default ruling for most things is halal unless specifically prohibited.", relatedTerms: ["haram"] },
    { id: "haram", term: "Haram", arabic: "حَرَام", category: "Jurisprudence", definition: "Forbidden, prohibited, what the shari'ah prohibits outright (e.g., alcohol, pork, interest, theft, adultery).", relatedTerms: ["halal", "makruh"] },
    { id: "makruh", term: "Makruh", arabic: "مَكْرُوه", category: "Jurisprudence", definition: "Disliked, not sinful but disapproved. Abandoning the makruh is rewarded; doing it is not punished.", relatedTerms: ["haram", "mustahabb"] },
    { id: "mustahabb", term: "Mustahabb / Sunnah / Mandub", arabic: "مُسْتَحَبّ", category: "Jurisprudence", definition: "Recommended, acts that are rewarded if done but not sinful if left. Praying sunnah raka'at, growing a beard, etc.", relatedTerms: ["fardh", "makruh"] },
    { id: "fardh", term: "Fardh", arabic: "فَرْض", category: "Jurisprudence", definition: "Obligatory, acts Allah commanded that one is sinful for abandoning. The five daily prayers, zakat, fasting Ramadan, Hajj (once).", relatedTerms: ["wajib"] },
    { id: "wajib", term: "Wajib", arabic: "وَاجِب", category: "Jurisprudence", definition: "Obligatory, in most schools synonymous with fardh. The Hanafi school distinguishes wajib (based on probable evidence) from fardh (based on certain evidence).", relatedTerms: ["fardh"] },
    { id: "mubah", term: "Mubah", arabic: "مُبَاح", category: "Jurisprudence", definition: "Neutral, permitted, neither rewarded nor punished, and neither commanded nor prohibited. The default of most mundane acts.", relatedTerms: ["halal"] },
    { id: "sharia", term: "Shari'ah", arabic: "الشَّرِيعَة", category: "Jurisprudence", definition: "Islamic law, the totality of rulings derived from Quran, Sunnah, consensus (ijma'), and analogy (qiyas). Covers worship, dealings, family, criminal law, and ethics.", relatedTerms: ["fiqh", "usul"] },
    { id: "fiqh", term: "Fiqh", arabic: "الفِقْه", category: "Jurisprudence", definition: "Islamic jurisprudence, the scholarly understanding and derivation of rulings from the primary sources. The four Sunni schools: Hanafi, Maliki, Shafi'i, Hanbali.", relatedTerms: ["sharia", "madhhab"] },
    { id: "madhhab", term: "Madhhab", arabic: "مَذْهَب", plural: "Madhahib", category: "Jurisprudence", definition: "A school of fiqh. The four recognized Sunni schools: Hanafi, Maliki, Shafi'i, Hanbali, each named after its founding imam.", relatedTerms: ["fiqh"] },
    { id: "ijma", term: "Ijma'", arabic: "الإِجْمَاع", category: "Jurisprudence", definition: "Scholarly consensus, the unanimous agreement of the qualified jurists of a generation on a ruling. The third source of Islamic law.", relatedTerms: ["qiyas"] },
    { id: "qiyas", term: "Qiyas", arabic: "القِيَاس", category: "Jurisprudence", definition: "Analogical reasoning, extending a known ruling to a new case based on a shared effective cause ('illah). The fourth source of law.", relatedTerms: ["ijma"] },
    { id: "ijtihad", term: "Ijtihad", arabic: "الاجْتِهَاد", category: "Jurisprudence", definition: "Independent legal reasoning, the exertion of effort by a qualified scholar to derive rulings from the sources.", relatedTerms: ["mujtahid"] },
    { id: "fatwa", term: "Fatwa", arabic: "الفَتْوَى", plural: "Fatawa", category: "Jurisprudence", definition: "A scholarly legal opinion, issued by a qualified jurist (mufti) in response to a specific question. Not binding on anyone but the questioner unless they accept it.", relatedTerms: ["mufti"] },
    { id: "mufti", term: "Mufti", arabic: "مُفْتِي", category: "Jurisprudence", definition: "A qualified jurist authorized to issue fatwas.", relatedTerms: ["fatwa"] },
    { id: "nisab", term: "Nisab", arabic: "النِّصَاب", category: "Jurisprudence", definition: "The minimum threshold of wealth above which zakat becomes obligatory, 85 grams of gold or equivalent (roughly). Held for one lunar year (hawl).", relatedTerms: ["zakat"] },
    { id: "riba", term: "Riba", arabic: "الرِّبَا", category: "Jurisprudence", definition: "Usury or interest, strictly forbidden in Islam. The Quran describes riba as waging 'war against Allah and His Messenger' (2:279).", relatedTerms: ["haram"] },
    { id: "halal-food", term: "Dhabihah", arabic: "الذَّبِيحَة", category: "Jurisprudence", definition: "Islamic slaughter, the method required for meat to be halal: mention of Allah's name, a sharp blade, cutting the arteries swiftly.", relatedTerms: ["halal"] },

    // --- Community & Society ---
    { id: "ummah", term: "Ummah", arabic: "الأُمَّة", category: "Community & Society", definition: "The global Muslim community, bound by faith, not by ethnicity, nationality, or language.", relatedTerms: ["jamaah"] },
    { id: "jamaah", term: "Jama'ah", arabic: "الجَمَاعَة", category: "Community & Society", definition: "Congregation or community, especially the congregational prayer, and the mainstream body of Muslims following the Sunnah.", relatedTerms: ["ummah"] },
    { id: "imam", term: "Imam", arabic: "الإِمَام", category: "Community & Society", definition: "Leader, of prayer, of a mosque, or of a community. Also used historically for the founding scholars of the madhhabs.", relatedTerms: ["khalifa"] },
    { id: "khalifa", term: "Khalifah", arabic: "الخَلِيفَة", plural: "Khulafa", category: "Community & Society", definition: "Successor, vicegerent, historically the leader of the Muslim ummah after the Prophet ﷺ. The Rightly-Guided Caliphs (Khulafa ar-Rashidun) were Abu Bakr, 'Umar, 'Uthman, and 'Ali.", relatedTerms: ["imam", "sahaba"] },
    { id: "sahaba", term: "Sahabah", arabic: "الصَّحَابَة", category: "Community & Society", definition: "The Companions of the Prophet ﷺ, those who met him as believers and died as believers. The best of generations.", relatedTerms: ["tabiun"] },
    { id: "tabiun", term: "Tabi'un", arabic: "التَّابِعُون", category: "Community & Society", definition: "'The followers', the generation after the Sahabah who met them but not the Prophet ﷺ.", relatedTerms: ["sahaba"] },
    { id: "muhajir", term: "Muhajir / Muhajirun", arabic: "المُهَاجِرُون", category: "Community & Society", definition: "The 'emigrants', the Companions who migrated from Mecca to Medina.", relatedTerms: ["ansar", "hijra"] },
    { id: "ansar", term: "Ansar", arabic: "الأَنْصَار", category: "Community & Society", definition: "The 'helpers', the Muslims of Medina who received the Muhajirun, sharing their homes and wealth.", relatedTerms: ["muhajir"] },
    { id: "masjid", term: "Masjid", arabic: "المَسْجِد", plural: "Masajid", category: "Community & Society", definition: "A mosque, literally 'a place of prostration.' The three holiest are Masjid al-Haram (Mecca), Masjid an-Nabawi (Medina), and Masjid al-Aqsa (Jerusalem).", relatedTerms: ["jamaah"] },
    { id: "musallah", term: "Musalla", arabic: "المُصَلَّى", category: "Community & Society", definition: "A prayer space, smaller than a masjid, often a designated room or open area without the full rulings of a masjid.", relatedTerms: ["masjid"] },
    { id: "mihrab", term: "Mihrab", arabic: "المِحْرَاب", category: "Community & Society", definition: "The niche in a mosque indicating the direction of the Ka'bah (qiblah).", relatedTerms: ["qibla", "masjid"] },
    { id: "minbar", term: "Minbar", arabic: "المِنْبَر", category: "Community & Society", definition: "The pulpit in the mosque from which the imam delivers the Friday khutbah.", relatedTerms: ["khutbah", "masjid"] },
    { id: "nikah", term: "Nikah", arabic: "النِّكَاح", category: "Community & Society", definition: "Islamic marriage contract, requires the consent of both parties, witnesses, a wali for the bride, and mahr (dower).", relatedTerms: ["mahr", "walima"] },
    { id: "mahr", term: "Mahr", arabic: "المَهْر", category: "Community & Society", definition: "The obligatory gift (dowry) from the groom to the bride at marriage, her property alone.", relatedTerms: ["nikah"] },
    { id: "walima", term: "Walima", arabic: "الوَلِيمَة", category: "Community & Society", definition: "The wedding feast hosted by the groom after consummation, a sunnah strongly emphasized by the Prophet ﷺ.", relatedTerms: ["nikah"] },
    { id: "talaq", term: "Talaq", arabic: "الطَّلَاق", category: "Community & Society", definition: "Divorce, a permissible but disliked act in Islam. 'The most hated of permitted things to Allah is divorce.'", relatedTerms: ["nikah"] },

    // --- Eschatology ---
    { id: "akhira", term: "Al-Akhirah", arabic: "الآخِرَة", category: "Eschatology", definition: "The hereafter, the eternal life after death, beginning with the grave and including resurrection, judgment, and paradise or hellfire.", relatedTerms: ["qiyama", "jannah", "jahannam"] },
    { id: "qiyama", term: "Yawm al-Qiyamah", arabic: "يَوْم القِيَامَة", category: "Eschatology", definition: "The Day of Resurrection / Day of Judgment, when every soul will be raised and held accountable.", relatedTerms: ["akhira", "hisab"] },
    { id: "hisab", term: "Hisab", arabic: "الحِسَاب", category: "Eschatology", definition: "The reckoning, the judgment each person undergoes for their deeds, with the records of angels as witnesses.", relatedTerms: ["qiyama", "mizan"] },
    { id: "mizan", term: "Mizan", arabic: "المِيزَان", category: "Eschatology", definition: "The scale on which deeds will be weighed on the Day of Judgment.", relatedTerms: ["hisab"] },
    { id: "sirat", term: "As-Sirat", arabic: "الصِّرَاط", category: "Eschatology", definition: "The bridge over Hellfire each person must cross on the Day of Judgment, some will cross in an instant, some will fall.", relatedTerms: ["akhira"] },
    { id: "jannah", term: "Jannah", arabic: "الجَنَّة", plural: "Jannat", category: "Eschatology", definition: "Paradise, the eternal garden of reward for the righteous. The Quran describes rivers of water, milk, honey, and wine, with every desire fulfilled.", relatedTerms: ["akhira", "firdaws"] },
    { id: "firdaws", term: "Al-Firdaws", arabic: "الفِرْدَوْس", category: "Eschatology", definition: "The highest level of Paradise, the goal every believer is taught to ask for in du'a.", relatedTerms: ["jannah"] },
    { id: "jahannam", term: "Jahannam", arabic: "جَهَنَّم", category: "Eschatology", definition: "Hellfire, the abode of punishment for those who reject Allah. Described with terrifying imagery in the Quran.", relatedTerms: ["akhira"] },
    { id: "barzakh", term: "Al-Barzakh", arabic: "البَرْزَخ", category: "Eschatology", definition: "The intermediate state between death and resurrection, the life in the grave.", relatedTerms: ["akhira"] },
    { id: "dajjal", term: "Al-Masih ad-Dajjal", arabic: "المَسِيح الدَّجَّال", category: "Eschatology", definition: "'The False Messiah', a figure who will appear near the end of time claiming divinity, spreading fitnah. 'Isa ﷺ will descend and kill him.", relatedTerms: ["isa-return", "akhira"] },
    { id: "mahdi", term: "Al-Mahdi", arabic: "المَهْدِي", category: "Eschatology", definition: "'The Guided One', a descendant of the Prophet ﷺ who will appear before the end of time to restore justice.", relatedTerms: ["akhira"] },

    // --- Seerah / History terms ---
    { id: "hijra", term: "Hijrah", arabic: "الهِجْرَة", category: "Seerah & History", definition: "The migration of the Prophet ﷺ from Mecca to Medina in 622 CE, the event from which the Islamic calendar (AH) begins.", relatedTerms: ["muhajir"] },
    { id: "jahiliyya", term: "Jahiliyyah", arabic: "الجَاهِلِيَّة", category: "Seerah & History", definition: "'The age of ignorance', the pre-Islamic period of Arabia (and by extension, any condition of spiritual and moral ignorance).", relatedTerms: ["hijra"] },
    { id: "isra-miraj", term: "Al-Isra wal-Mi'raj", arabic: "الإِسْرَاء والمِعْرَاج", category: "Seerah & History", definition: "The Night Journey (from Mecca to Al-Aqsa) and the Ascension (through the heavens) of the Prophet ﷺ, when the five daily prayers were ordained.", relatedTerms: ["salah"] },
    { id: "sunnah-practice", term: "Sunnah (Practice)", arabic: "سُنَّة", category: "Seerah & History", definition: "Also: the Prophet's ﷺ living example, the way he dressed, ate, slept, greeted, traveled, worshipped, and treated people. The second primary source of Islam.", relatedTerms: ["hadith"] },

    // --- Daily utterances ---
    { id: "salam", term: "As-Salamu 'alaykum", arabic: "السَّلَامُ عَلَيْكُم", category: "Daily Practice", definition: "'Peace be upon you', the Islamic greeting. Full form: 'As-salamu 'alaykum wa rahmatullahi wa barakatuh.' Reply: 'Wa 'alaykumus-salam.'", relatedTerms: [] },
    { id: "inshaallah", term: "In sha' Allah", arabic: "إِنْ شَاءَ اللَّه", category: "Daily Practice", definition: "'If Allah wills', said when speaking of any future plan or intention. Commanded in Surah Al-Kahf (18:23-24).", relatedTerms: [] },
    { id: "alhamdulillah", term: "Alhamdulillah", arabic: "الحَمْدُ لِلَّه", category: "Daily Practice", definition: "'All praise is due to Allah', a foundational phrase of gratitude said after eating, sneezing, receiving good news, or at any time.", relatedTerms: ["shukr"] },
    { id: "subhanallah", term: "Subhan Allah", arabic: "سُبْحَانَ اللَّه", category: "Daily Practice", definition: "'Glory be to Allah', a statement of tasbih, affirming Allah's perfection above any deficiency.", relatedTerms: [] },
    { id: "allahuakbar", term: "Allahu Akbar", arabic: "اللَّهُ أَكْبَر", category: "Daily Practice", definition: "'Allah is the Greatest', takbir. Opens every prayer, signals transitions within it, and is said in moments of awe, hardship, and joy.", relatedTerms: ["salah"] },
    { id: "mashallah", term: "Ma sha' Allah", arabic: "مَا شَاءَ اللَّه", category: "Daily Practice", definition: "'As Allah willed', said when witnessing something good or beautiful, to acknowledge the blessing is from Him.", relatedTerms: [] },
    { id: "astaghfirullah", term: "Astaghfirullah", arabic: "أَسْتَغْفِرُ اللَّه", category: "Daily Practice", definition: "'I seek Allah's forgiveness', the verbal form of istighfar, said after a sin or at any time.", relatedTerms: ["istighfar", "tawba"] },
    { id: "jazakallah", term: "Jazak Allahu khayran", arabic: "جَزَاكَ اللَّهُ خَيْرًا", category: "Daily Practice", definition: "'May Allah reward you with good', the prophetic way of saying thank you. Reply: 'Wa iyyak' ('and you also').", relatedTerms: [] },
    { id: "bismillah2", term: "Bismillah (said daily)", arabic: "بِسْمِ اللَّه", category: "Daily Practice", definition: "Also: said before every significant action, eating, drinking, entering the home, beginning a journey, writing. Invokes Allah's name for barakah.", relatedTerms: ["bismillah"] },
    { id: "dua", term: "Du'a", arabic: "الدُّعَاء", category: "Daily Practice", definition: "Supplication, any personal prayer or asking of Allah, in any language, at any time. 'Du'a is the essence of worship.'", relatedTerms: ["salah"] },
    { id: "dhikr", term: "Dhikr", arabic: "الذِّكْر", category: "Daily Practice", definition: "Remembrance of Allah, through phrases (subhanallah, alhamdulillah, etc), recitation, or silent awareness. 'Verily, in the remembrance of Allah do hearts find rest' (13:28).", relatedTerms: ["dua", "tasbih"] },
    { id: "tasbih", term: "Tasbih", arabic: "التَّسْبِيح", category: "Daily Practice", definition: "Glorification, specifically saying 'Subhan Allah.' Also refers to prayer beads used to count dhikr.", relatedTerms: ["dhikr"] },
];
